### ISSUE TITLE
make error (ubuntu 10.04)

### ISSUE THREAD

**Issue by dynnamitt** [rsaarelm/teratogen#2]
excerpt:
....
......
........
/home/kdm/bin/8g -o _go_.8 fs.go 
fs.go:117: undefined: gzip.NewReader

Any Idea?

**Comment by dynnamitt** [comment]
## full stdout:

$ make all
/home/kdm/bin/gomake -C pkg deps
make[1]: Entering directory `/home/kdm/devo/go1/teratogen/pkg'
/home/kdm/go/src/pkg/deps.bash
make[1]: Leaving directory`/home/kdm/devo/go1/teratogen/pkg'
/home/kdm/bin/gomake -C pkg all
make[1]: Entering directory `/home/kdm/devo/go1/teratogen/pkg'
/home/kdm/go/src/pkg/deps.bash
/home/kdm/bin/gomake -C gostak install
make[2]: Entering directory`/home/kdm/devo/go1/teratogen/pkg/gostak'
/home/kdm/bin/8g -o _go_.8 gostak.go 
rm -f _obj/gostak.a
/home/kdm/bin/gopack grc _obj/gostak.a _go_.8 
cp _obj/gostak.a "/home/kdm/go/pkg/linux_386/gostak.a"
make[2]: Leaving directory `/home/kdm/devo/go1/teratogen/pkg/gostak'
/home/kdm/bin/gomake -C hyades/dbg install
make[2]: Entering directory`/home/kdm/devo/go1/teratogen/pkg/hyades/dbg'
/home/kdm/bin/8g -o _go_.8 debug.go 
rm -f _obj/hyades/dbg.a
/home/kdm/bin/gopack grc _obj/hyades/dbg.a _go_.8 
cp _obj/hyades/dbg.a "/home/kdm/go/pkg/linux_386/hyades/dbg.a"
make[2]: Leaving directory `/home/kdm/devo/go1/teratogen/pkg/hyades/dbg'
/home/kdm/bin/gomake -C hyades/mem install
make[2]: Entering directory`/home/kdm/devo/go1/teratogen/pkg/hyades/mem'
/home/kdm/bin/8g -o _go_.8 blank.go mem.go serialize.go 
rm -f _obj/hyades/mem.a
/home/kdm/bin/gopack grc _obj/hyades/mem.a _go_.8 
cp _obj/hyades/mem.a "/home/kdm/go/pkg/linux_386/hyades/mem.a"
make[2]: Leaving directory `/home/kdm/devo/go1/teratogen/pkg/hyades/mem'
/home/kdm/bin/gomake -C hyades/alg install
make[2]: Entering directory`/home/kdm/devo/go1/teratogen/pkg/hyades/alg'
/home/kdm/bin/8g -o _go_.8 alg.go bktree.go graph.go iter.go set.go 
rm -f _obj/hyades/alg.a
/home/kdm/bin/gopack grc _obj/hyades/alg.a _go_.8 
cp _obj/hyades/alg.a "/home/kdm/go/pkg/linux_386/hyades/alg.a"
make[2]: Leaving directory `/home/kdm/devo/go1/teratogen/pkg/hyades/alg'
/home/kdm/bin/gomake -C hyades/babble install
make[2]: Entering directory`/home/kdm/devo/go1/teratogen/pkg/hyades/babble'
/home/kdm/bin/8g -o _go_.8 babble.go 
rm -f _obj/hyades/babble.a
/home/kdm/bin/gopack grc _obj/hyades/babble.a _go_.8 
cp _obj/hyades/babble.a "/home/kdm/go/pkg/linux_386/hyades/babble.a"
make[2]: Leaving directory `/home/kdm/devo/go1/teratogen/pkg/hyades/babble'
/home/kdm/bin/gomake -C hyades/entity install
make[2]: Entering directory`/home/kdm/devo/go1/teratogen/pkg/hyades/entity'
/home/kdm/bin/8g -o _go_.8 container.go manager.go relation.go template.go util.go 
rm -f _obj/hyades/entity.a
/home/kdm/bin/gopack grc _obj/hyades/entity.a _go_.8 
cp _obj/hyades/entity.a "/home/kdm/go/pkg/linux_386/hyades/entity.a"
make[2]: Leaving directory `/home/kdm/devo/go1/teratogen/pkg/hyades/entity'
/home/kdm/bin/gomake -C hyades/fs install
make[2]: Entering directory`/home/kdm/devo/go1/teratogen/pkg/hyades/fs'
/home/kdm/bin/8g -o _go_.8 fs.go 
fs.go:117: undefined: gzip.NewReader
make[2]: **\* [_go_.8] Error 1
make[2]: Leaving directory `/home/kdm/devo/go1/teratogen/pkg/hyades/fs'
make[1]: *** [hyades/fs.install] Error 2
make[1]: Leaving directory`/home/kdm/devo/go1/teratogen/pkg'
make: **\* [build.libs] Error 2

**Comment by rsaarelm** [comment]
This was a recent API change in the Go standard library. Your Go environment is probably out of date.

**Comment by dynnamitt** [comment]
Aha! I'm not sure what version Im using but it's probably not bleeding edge..
